baseurl = "https://cybercafe.dev/"
title = "cybercafe.dev"
author = "amt8u"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"

